image:
  repository: ghcr.io/thedevminertv/veilid-chat
  pullPolicy: Always
  tag: "latest"

replicas: 1

service:
  port: 80
  host: dev.vldchat.devminer.xyz
  ssl:
    enabled: true
    port: 443
    issuer:
      name: letsencrypt
      kind: ClusterIssuer

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 16Mi
