---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vldchat.fullname" . }}
  labels:
    {{- include "vldchat.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "vldchat.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vldchat.fullname" . }}-canary
  labels:
    {{- include "vldchat.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "vldchat.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
      protocol: TCP
